export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_ERRORS = "REGISTER_ERRORS";
export const LOGIN_ERRORS = "LOGIN_ERRORS";
export const UPDATE_USER_STATE_ON_TOKEN = "UPDATE_USER_STATE_ON_TOKEN";
